version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_NAME=esokoservicemanager
      - DB_USERNAME=sam
      - DB_PASSWORD=areuDAYcare
      - DB_HOST=db
      - JWT_SECRET=VbA49GS2i0P8sLz5mCxj1N0hF7eR9dWy
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=esokoservicemanager
      - POSTGRES_USER=sam
      - POSTGRES_PASSWORD=areuDAYcare
